/**
 * code borrowed from node_redis
 */
var request = require('request');
var co = require('co');
var fs = require('fs');
var get = co.wrap(request.get);
function prettyCurrentTime() {
    var date = new Date();
    return date.toLocaleString();
}
co(function* () {
  var path = 'commands.js';
  var file_contents = "// This file was generated by ./generate_commands.js on " + prettyCurrentTime() + "\n";
  var result = yield get('http://redis.io/commands.json');
  var commands = Object.keys(JSON.parse(result[1]));
  file_contents += "module.exports = " + JSON.stringify(commands, null, "\t") + ";\n";
  fs.writeFile(path, file_contents);
});